### ISSUE TITLE
[tally] introduce 'invoice' to support dot-matrix printer's multi-connected carbon paper

### ISSUE THREAD

**Issue by 0xffff00** [0xffff00/skfe#8]
invoice's data should be unified to tally & deal
tally <--1----n-- invoice <--1----n-- deal

**Comment by 0xffff00** [comment]
淘宝上买到的常见多联复写打印纸（241mm×279.4mm,针式打印机用）
二等分后变成241mm×139.7mm，其css设置如下
```css
    @media print {
        @page {
            size: 241mm 139.7mm;
            margin: 0 10mm 5mm 10mm;
        }
    }
```
